using System.Globalization;
using System.Text.Json;
using CYAC.Port.Core.Model.Mission;
using CYAC.Port.Host.Configuration;
using CYAC.Port.Host.FrontEnd;

namespace CYAC.Port.Host.Settings;

/// <summary>
/// The port's own <c>settings.json</c>: where it lives, what it holds, and the PRECEDENCE that
/// decides which value a run actually flies with.
/// </summary>
/// <remarks>
/// <para>
/// <b>Where.</b>  Beside the data tree's PARENT — <c>&lt;data root&gt;/../settings.json</c>, the repo
/// root when the port runs out of the checkout — overridable with <c>--settings &lt;path&gt;</c>.
/// It is deliberately NOT inside <c>data/</c>: that tree is regenerated by <c>cyac-transform</c> and
/// census-gated (the transform-first law), so a hand-edited file in it would be destroyed by the
/// next regeneration and would break the census.
/// </para>
/// <para>
/// <b>Precedence: built-in default &lt; <c>settings.json</c> &lt; the command line.</b> A value
/// given on the command line wins for that run and is <b>not</b> written back — the file keeps
/// whatever it held (or the default) until the DIALOG changes that row.  That is why the store keeps
/// two maps: <see cref="_live"/>, what the run is flying with, and <see cref="_file"/>, what the next
/// <see cref="Save"/> will write.
/// </para>
/// <para>
/// <b>Atomic writes.</b>  Every change from the dialog rewrites the whole file through a temp file
/// and a rename, so a crash mid-write can never leave a half-written settings file behind — the
/// worst case is the previous complete file.
/// </para>
/// </remarks>
public sealed class PortSettingsStore
{
    /// <summary>The file's own name.</summary>
    public const string FileName = "settings.json";

    /// <summary>What the file's <c>format</c> string says; a reader may key on it later.</summary>
    public const string FormatTag = "cyac-port-settings/1";

    private readonly Dictionary<string, SettingValue> _live = new(StringComparer.Ordinal);
    private readonly Dictionary<string, SettingValue> _file = new(StringComparer.Ordinal);
    private readonly HashSet<string> _fromCommandLine = new(StringComparer.Ordinal);
    private readonly List<string> _warnings = [];
    private readonly FlyOptions _options;
    private FlightRasterizer? _host;

    private PortSettingsStore(string path, FlyOptions options)
    {
        Path = path;
        _options = options;
    }

    /// <summary>The resolved settings-file path — what the readout's first line names.</summary>
    public string Path { get; }

    /// <summary>Whether the file existed and parsed when the run started.</summary>
    public bool FileLoaded { get; private set; }

    /// <summary>
    /// The last sortie the player started, or null when nothing has been flown yet.
    /// </summary>
    /// <remarks>
    /// The menu's <c>Last Mission</c> row (strings.json 14) is greyed until this exists.  It lives
    /// beside the settings rather than in <c>stats.json</c> for M3 §4.5's reason: the statistics file
    /// is an append-only record and a corrupt "what was I doing" line must not cost it.  It is not a
    /// save game and not progression — all 50 missions stay open.
    /// </remarks>
    public LastSortie? LastSortie { get; private set; }

    /// <summary>How many settings the file supplied.</summary>
    public int FromFile { get; private set; }

    /// <summary>How many settings the command line overrode for this run.</summary>
    public int FromCommandLine => _fromCommandLine.Count;

    /// <summary>How many times the dialog has written the file.</summary>
    public int Writes { get; private set; }

    /// <summary>Anything wrong with the file — a parse failure, an unknown key, a bad type.</summary>
    public IReadOnlyList<string> Warnings => _warnings;

    /// <summary>The value in force for a setting.</summary>
    /// <param name="setting">The setting.</param>
    public SettingValue Value(PortSetting setting)
    {
        ArgumentNullException.ThrowIfNull(setting);
        return _live.TryGetValue(setting.Name, out SettingValue value) ? value : setting.Default;
    }

    /// <summary>Whether the setting is at its built-in default.</summary>
    /// <param name="setting">The setting.</param>
    public bool IsDefault(PortSetting setting)
    {
        ArgumentNullException.ThrowIfNull(setting);
        return setting.Same(Value(setting), setting.Default);
    }

    /// <summary>Whether the command line pinned this setting for the run.</summary>
    /// <param name="setting">The setting.</param>
    public bool IsFromCommandLine(PortSetting setting)
    {
        ArgumentNullException.ThrowIfNull(setting);
        return _fromCommandLine.Contains(setting.Name);
    }

    /// <summary>
    /// Where <c>settings.json</c> goes for a data tree: beside the tree's PARENT directory.
    /// </summary>
    /// <param name="dataRoot">The data tree's own root directory.</param>
    /// <param name="over">The <c>--settings</c> override, or null.</param>
    public static string Resolve(string dataRoot, string? over)
    {
        if (!string.IsNullOrWhiteSpace(over))
        {
            string full = System.IO.Path.GetFullPath(over);
            return Directory.Exists(full) ? System.IO.Path.Combine(full, FileName) : full;
        }

        string? parent = Directory.GetParent(System.IO.Path.GetFullPath(dataRoot))?.FullName;
        return System.IO.Path.Combine(parent ?? System.IO.Path.GetFullPath(dataRoot), FileName);
    }

    /// <summary>
    /// Builds the store: defaults, then the file, then the command line — and writes the result back
    /// into the options everything else is built from.
    /// </summary>
    /// <param name="path">The resolved settings-file path.</param>
    /// <param name="options">The parsed command line (mutated to hold the resolved values).</param>
    /// <param name="commandLineNames">
    /// The long option names that actually appeared on the command line, which is what makes the
    /// third precedence level knowable — <see cref="NamesOnCommandLine"/> reads them off argv.
    /// </param>
    public static PortSettingsStore Open(
        string path, FlyOptions options, IReadOnlyCollection<string> commandLineNames)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(commandLineNames);
        PortSettingsStore store = new PortSettingsStore(path, options);

        // 1 — the built-in defaults.
        foreach (PortSetting setting in PortSettings.All)
        {
            store._live[setting.Name] = setting.Default;
            store._file[setting.Name] = setting.Default;
        }

        // 2 — the file.
        store.ReadFile();

        // 3 — the command line, for this run only.
        foreach (PortSetting setting in PortSettings.All)
        {
            if (commandLineNames.Contains(setting.Name))
            {
                store._fromCommandLine.Add(setting.Name);
                store._live[setting.Name] = setting.Normalise(setting.Read(options));
            }
        }

        // …and the result becomes what the host builds everything from.
        foreach (PortSetting setting in PortSettings.All)
        {
            setting.Write(options, store._live[setting.Name]);
        }

        return store;
    }

    /// <summary>
    /// Which of the table's settings were named on the command line.
    /// </summary>
    /// <param name="args">The process arguments.</param>
    /// <remarks>
    /// CommandLineParser does not report which options it actually saw, so the run reads argv — the
    /// port's settings all have LONG names only, so <c>--name</c> and <c>--name=value</c> are the
    /// only two spellings that can reach one.
    /// </remarks>
    public static HashSet<string> NamesOnCommandLine(IReadOnlyList<string> args)
    {
        ArgumentNullException.ThrowIfNull(args);
        HashSet<string> named = new HashSet<string>(StringComparer.Ordinal);
        foreach (string arg in args)
        {
            if (!arg.StartsWith("--", StringComparison.Ordinal))
            {
                continue;
            }

            int equals = arg.IndexOf('=', StringComparison.Ordinal);
            string name = equals >= 0 ? arg[2..equals] : arg[2..];
            if (PortSettings.Find(name) is not null)
            {
                named.Add(name);
            }

            // An explicit --windows word speaks for the four window rows, so it pins them for
            // this run exactly as naming each of them would (the file must not override a
            // probe's or a test's word).
            if (string.Equals(name, "windows", StringComparison.Ordinal))
            {
                foreach ((PortSetting setting, CockpitOverlayFlags _) in PortSettings.WindowRows)
                {
                    named.Add(setting.Name);
                }
            }
        }

        return named;
    }

    /// <summary>Remembers what a sortie was, and writes the file.</summary>
    /// <param name="sortie">The sortie that has just been STARTED.</param>
    /// <remarks>
    /// Written at the sortie's start, not its end, so a crash or a Ctrl-C mid-sortie still leaves the
    /// row usable.  An identical repeat writes nothing.
    /// </remarks>
    public void Remember(LastSortie sortie)
    {
        ArgumentNullException.ThrowIfNull(sortie);
        if (LastSortie == sortie)
        {
            return;
        }

        LastSortie = sortie;
        Save();
    }

    /// <summary>Lets go of the rasterizer when its sortie ends.</summary>
    /// <remarks>
    /// Without it the store would keep pushing live values into a DISPOSED rasterizer while the
    /// player is in the menu.  The next sortie's <see cref="Attach"/> re-pushes everything.
    /// </remarks>
    public void Detach()
    {
        if (_host is { } host)
        {
            host.OverlaysChanged -= MirrorWindows;
        }

        _host = null;
    }

    /// <summary>Gives the store the rasterizer whose live state a change has to reach.</summary>
    /// <param name="host">The rasterizer.</param>
    /// <remarks>
    /// Every LIVE setting is pushed once here as well, so a value that came out of the file reaches
    /// the surfaces the constructor does not read (the menu's own opacity and scale, the sound
    /// mixer) without a second code path.
    /// </remarks>
    public void Attach(FlightRasterizer host)
    {
        _host = host;
        foreach (PortSetting setting in PortSettings.All)
        {
            setting.Apply?.Invoke(host, Value(setting));
        }

        // A Shift-1..4 press at the window changes the live overlay byte; the four window rows
        // follow it (and the file remembers it, as yeager.cfg@0x1D did).
        host.OverlaysChanged += MirrorWindows;
    }

    /// <summary>
    /// The four window rows take the LIVE overlay byte after a key press: no <c>Apply</c>
    /// (it is the live state already), the option word and the file updated.
    /// </summary>
    /// <param name="mask">The overlay mask after the press.</param>
    internal void MirrorWindows(CockpitOverlayFlags mask)
    {
        bool changed = false;
        foreach ((PortSetting setting, CockpitOverlayFlags window) in PortSettings.WindowRows)
        {
            SettingValue value = SettingValue.Toggle(mask.HasFlag(window));
            if (setting.Same(Value(setting), value))
            {
                continue;
            }

            _live[setting.Name] = value;
            _file[setting.Name] = value;
            _fromCommandLine.Remove(setting.Name);
            setting.Write(_options, value);
            changed = true;
        }

        if (changed)
        {
            Save();
        }
    }

    /// <summary>
    /// Changes one setting: the live state, the options a restart rebuilds from, and the file.
    /// </summary>
    /// <param name="setting">The setting.</param>
    /// <param name="value">Its new value (normalised here).</param>
    /// <returns>True when the value really changed.</returns>
    public bool Set(PortSetting setting, SettingValue value)
    {
        ArgumentNullException.ThrowIfNull(setting);
        SettingValue normalised = setting.Normalise(value);
        if (setting.Same(Value(setting), normalised))
        {
            return false;
        }

        _live[setting.Name] = normalised;
        _file[setting.Name] = normalised;

        // A value the DIALOG chose is the file's now, so it stops being a command-line pin.
        _fromCommandLine.Remove(setting.Name);

        setting.Write(_options, normalised);
        if (_host is { } host)
        {
            setting.Apply?.Invoke(host, normalised);
        }

        Save();
        return true;
    }

    /// <summary>Resets one setting to its built-in default.</summary>
    /// <param name="setting">The setting.</param>
    /// <returns>True when it was not already there.</returns>
    public bool Reset(PortSetting setting)
    {
        ArgumentNullException.ThrowIfNull(setting);
        return Set(setting, setting.Default);
    }

    /// <summary>
    /// Writes the whole file — every setting, each with the <c>$comment</c> that repeats its help.
    /// </summary>
    /// <remarks>
    /// Atomic: a temp file beside the target, then a rename over it.  A directory that cannot be
    /// written is a WARNING, never a crash — the game keeps flying with the values it has.
    /// </remarks>
    public void Save()
    {
        // The temp-file-and-rename is AtomicJson's now, shared with stats.json so the two
        // port-owned files cannot drift apart in how they are written.
        string? trouble = WriteTo(Path);

        if (trouble is null)
        {
            Writes++;
            return;
        }

        Warn(trouble);
    }

    /// <summary>
    /// Writes the document <see cref="Save"/> would write, but to another path, and changes nothing else:
    /// not the store's own file, not its counters.  The startup check round-trips the loaded state through
    /// such a copy so an existing file is never rewritten just to prove it can be.
    /// </summary>
    /// <param name="path">Where to write.</param>
    /// <returns>A warning, or null when the write succeeded.</returns>
    internal string? SaveCopy(string path) => WriteTo(path);

    private string? WriteTo(string path) => AtomicJson.Write(path, writer =>
    {
        writer.WriteStartObject();
        writer.WriteString("format", FormatTag);
        foreach (PortSetting setting in PortSettings.All)
        {
            SettingValue value = _file.TryGetValue(setting.Name, out SettingValue held)
                ? held
                : setting.Default;
            writer.WriteStartObject(setting.Name);

            // The file is meant to be READ and hand-edited, so every entry repeats its own
            // help text — and AtomicJson's relaxed encoder keeps an apostrophe in that text
            // an apostrophe.
            writer.WriteString("$comment", setting.Help);
            switch (setting.Kind)
            {
                case PortSettingKind.Toggle:
                    writer.WriteBoolean("value", value.Flag);
                    break;
                case PortSettingKind.Choice:
                    writer.WriteString("value", value.Word);
                    break;
                case PortSettingKind.Color or PortSettingKind.Bits:
                    writer.WriteNumber("value", (int)Math.Round(value.Number));
                    break;
                default:
                    writer.WriteNumber(
                        "value",
                        Math.Round(value.Number, Math.Max(setting.Decimals, 0)));
                    break;
            }

            writer.WriteEndObject();
        }

        // The menu's Last Mission memory.  It is NOT a PortSetting (it has no default, no dialog
        // row and no command-line twin), so it is written here, after the table, and the reader
        // skips it by name.
        if (LastSortie is { } last)
        {
            writer.WriteStartObject(LastSortieKey);
            writer.WriteString(
                "$comment",
                "What the CHOOSE ACTIVITY menu's \"Last Mission\" row re-flies. Written when a "
                    + "sortie STARTS. Delete this object to grey the row again; it is not "
                    + "progression - every mission is open.");
            writer.WriteString("kind", last.Kind);
            writer.WriteNumber("slot", last.Slot);
            writer.WriteNumber("difficulty", last.Difficulty);
            writer.WriteString("aircraft", last.Aircraft);
            writer.WriteNumber("site", last.Site);

            // A CUSTOM mission's seven picks, as the hex of the original's own value array
            // (the 0x28 bytes of [0xC2E4] the fly exit saves, image@0x27774).  Written only
            // when there are any, so the historic/Test-Flight records are unchanged.
            if (last.Picks.Length > 0)
            {
                writer.WriteString("picks", last.Picks);
            }

            writer.WriteEndObject();
        }

        writer.WriteEndObject();
    });

    /// <summary>The readout's own first line: which file the run is using, and what it supplied.</summary>
    public string ReadoutLine()
    {
        string source = FileLoaded
            ? string.Create(CultureInfo.InvariantCulture, $"{FromFile} from file")
            : "no file - defaults";
        string pinned = FromCommandLine > 0
            ? string.Create(CultureInfo.InvariantCulture, $", {FromCommandLine} from command line")
            : string.Empty;
        string trouble = _warnings.Count > 0
            ? string.Create(CultureInfo.InvariantCulture, $"  ! {_warnings.Count} warning(s)")
            : string.Empty;
        return string.Create(
            CultureInfo.InvariantCulture,
            $"settings {AtomicJson.Short(Path)} ({source}{pinned}){trouble}");
    }

    private void ReadFile()
    {
        if (!File.Exists(Path))
        {
            return;
        }

        JsonDocument document;
        try
        {
            document = JsonDocument.Parse(File.ReadAllBytes(Path));
        }
        catch (Exception error) when (error is JsonException or IOException)
        {
            // A CORRUPT file is never fatal: the run flies on the built-in defaults and says so.
            Warn($"{Path} is not readable JSON ({error.Message}); the built-in defaults are used");
            return;
        }

        using (document)
        {
            if (document.RootElement.ValueKind != JsonValueKind.Object)
            {
                Warn($"{Path} is not a JSON object; the built-in defaults are used");
                return;
            }

            FileLoaded = true;
            foreach (JsonProperty property in document.RootElement.EnumerateObject())
            {
                if (string.Equals(property.Name, "format", StringComparison.Ordinal))
                {
                    continue;
                }

                if (string.Equals(property.Name, LastSortieKey, StringComparison.Ordinal))
                {
                    LastSortie = ReadLastSortie(property.Value);
                    continue;
                }

                if (PortSettings.Find(property.Name) is not { } setting)
                {
                    Warn($"{Path}: '{property.Name}' is not a port setting; ignored");
                    continue;
                }

                JsonElement element = property.Value;
                if (element.ValueKind == JsonValueKind.Object)
                {
                    if (!element.TryGetProperty("value", out element))
                    {
                        Warn($"{Path}: '{property.Name}' has no \"value\"; the default is used");
                        continue;
                    }
                }

                if (!TryRead(setting, element, out SettingValue value))
                {
                    Warn(
                        $"{Path}: '{property.Name}' holds a {element.ValueKind} where a "
                            + $"{setting.Kind} was expected; the default is used");
                    continue;
                }

                _live[setting.Name] = value;
                _file[setting.Name] = value;
                FromFile++;
            }
        }
    }

    /// <summary>The file's own name for the F1 Last Mission memory.</summary>
    public const string LastSortieKey = "lastSortie";

    /// <summary>Reads the Last Mission memory, tolerantly: anything malformed is simply absent.</summary>
    /// <param name="element">The <c>lastSortie</c> object.</param>
    private static LastSortie? ReadLastSortie(JsonElement element)
    {
        if (element.ValueKind != JsonValueKind.Object
            || !element.TryGetProperty("kind", out JsonElement kind)
            || kind.ValueKind != JsonValueKind.String)
        {
            return null;
        }

        string word = kind.GetString() ?? string.Empty;
        if (!string.Equals(word, FrontEnd.LastSortie.MissionKind, StringComparison.Ordinal)
            && !string.Equals(word, FrontEnd.LastSortie.TestFlightKind, StringComparison.Ordinal)
            && !string.Equals(word, FrontEnd.LastSortie.CustomKind, StringComparison.Ordinal))
        {
            return null;
        }

        string picks = element.TryGetProperty("picks", out JsonElement stored)
            && stored.ValueKind == JsonValueKind.String
                ? stored.GetString() ?? string.Empty
                : string.Empty;

        // A custom memory without its picks is not a custom memory: LastSortie.IsCustom
        // already says so, and a kind without them would grey nothing and fly nothing.
        if (string.Equals(word, FrontEnd.LastSortie.CustomKind, StringComparison.Ordinal)
            && picks.Length == 0)
        {
            return null;
        }

        return new LastSortie(
            word,
            Number(element, "slot", -1),
            Math.Clamp(Number(element, "difficulty", 1), 0, 3),
            element.TryGetProperty("aircraft", out JsonElement aircraft)
                && aircraft.ValueKind == JsonValueKind.String
                    ? aircraft.GetString() ?? string.Empty
                    : string.Empty,
            Number(element, "site", 0),
            picks);
    }

    private static int Number(JsonElement element, string name, int fallback) =>
        element.TryGetProperty(name, out JsonElement value)
            && value.ValueKind == JsonValueKind.Number
            && value.TryGetInt32(out int number)
                ? number
                : fallback;

    private static bool TryRead(PortSetting setting, JsonElement element, out SettingValue value)
    {
        value = setting.Default;
        switch (setting.Kind)
        {
            case PortSettingKind.Toggle:
                if (element.ValueKind is JsonValueKind.True or JsonValueKind.False)
                {
                    value = SettingValue.Toggle(element.GetBoolean());
                    return true;
                }

                if (element.ValueKind == JsonValueKind.String)
                {
                    value = setting.Normalise(PortSettings.Coerce(setting, element.GetString()));
                    return true;
                }

                return false;
            case PortSettingKind.Choice:
                if (element.ValueKind != JsonValueKind.String)
                {
                    return false;
                }

                string? word = element.GetString();
                if (!setting.Choices.Any(
                        c => string.Equals(c, word?.Trim(), StringComparison.OrdinalIgnoreCase)))
                {
                    return false;
                }

                value = setting.Normalise(SettingValue.Choice(word!));
                return true;
            default:
                if (element.ValueKind != JsonValueKind.Number
                    || !element.TryGetDouble(out double number))
                {
                    return false;
                }

                value = setting.Normalise(SettingValue.Of(number));
                return true;
        }
    }

    private void Warn(string message) => _warnings.Add(message);
}
