using System.Globalization;
using System.Text;
using CYAC.Port.Transform.Manifest;
using CYAC.Port.Transform.Transform;

namespace CYAC.Port.Transform;

/// <summary>
/// The generated <c>&lt;data&gt;/README.md</c>: what the tree holds, how to edit it, how to prove an
/// edit still round-trips.
/// </summary>
/// <remarks>
/// Each family contributes its own paragraph through <see cref="IFamilyTransform.TreeDescription"/>,
/// so a new family documents itself.
/// </remarks>
public static class DataTreeReadme
{
    /// <summary>The generated readme's file name.</summary>
    public const string FileName = "README.md";

    /// <summary>Renders the readme for one run.</summary>
    /// <param name="manifest">The manifest just written.</param>
    /// <param name="registry">The families the run applied.</param>
    public static byte[] Render(TransformManifest manifest, FamilyRegistry registry)
    {
        ArgumentNullException.ThrowIfNull(manifest);
        ArgumentNullException.ThrowIfNull(registry);

        StringBuilder text = new StringBuilder();
        text.AppendLine("# CYAC data tree");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture,
            $"Generated by `cyac-transform {TransformManifest.ToolVersion}` on {manifest.GeneratedUtc}");
        text.AppendLine(CultureInfo.InvariantCulture, $"from `{manifest.SourceDirectory}`.");
        text.AppendLine();
        text.AppendLine(manifest.SourceVerified
            ? $"Originals recognised as **{manifest.DistributionId}** — {manifest.DistributionDescription}"
            : "⚠ The originals matched **no known distribution** (`--allow-unknown-version`). " +
              "Everything here is stamped `source_verified: false`: treat it as unproven.");
        text.AppendLine();
        text.AppendLine("This tree is the **only** data the port reads. It contains no original game");
        text.AppendLine("code, and it is regenerated — never committed. Delete it and re-run the tool at will.");
        text.AppendLine();

        text.AppendLine("## What is here");
        text.AppendLine();
        text.AppendLine("- `manifest.json` — what was read (name, size, SHA-256), what was written, and how");
        text.AppendLine("  faithfully each output round-trips (`exact` / `canonical` / `lossy` / `generated`).");
        foreach (IFamilyTransform family in registry.All)
        {
            if (registry.IsSelected(family.Family))
            {
                text.AppendLine(CultureInfo.InvariantCulture, $"- {family.TreeDescription}");
            }
        }

        if (registry.TouchesArchives)
        {
            text.AppendLine("- `libs/<lib>/_directory.json` — one per EALIB archive: the container directory");
            text.AppendLine("  (member names, encoding flags, offsets, sizes) plus the file each member's content");
            text.AppendLine("  now lives in. Rebuilding those in index order reproduces the archive byte-for-byte.");
            text.AppendLine("- `libs/<lib>/<asset>.raw` — decoded members no family explains **yet**. They are");
            text.AppendLine("  carried verbatim so the round trip still closes, and counted as *unexplained bytes*:");
            text.AppendLine("  that number is the project's burn-down, not a permanent state.");
        }

        text.AppendLine();
        text.AppendLine("## Totals");
        text.AppendLine();
        text.AppendLine(
            "| family | outputs | exact | canonical | lossy | generated | unverified | unknown B | code B | unexplained B |");
        text.AppendLine("|:--|--:|--:|--:|--:|--:|--:|--:|--:|--:|");
        foreach (IGrouping<string, ManifestOutput> group in manifest.Outputs.GroupBy(o => o.Family).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            text.AppendLine(CultureInfo.InvariantCulture,
                $"| `{group.Key}` | {group.Count()} " +
                $"| {group.Count(o => o.Fidelity == OutputFidelity.Exact)} " +
                $"| {group.Count(o => o.Fidelity == OutputFidelity.Canonical)} " +
                $"| {group.Count(o => o.Fidelity == OutputFidelity.Lossy)} " +
                $"| {group.Count(o => o.Fidelity == OutputFidelity.Generated)} " +
                $"| {group.Count(o => o.Fidelity == OutputFidelity.Unverified)} " +
                $"| {group.Sum(o => o.UnknownBytes)} | {group.Sum(o => o.CodeBytes)} " +
                $"| {group.Sum(o => o.UnexplainedBytes)} |");
        }

        text.AppendLine(CultureInfo.InvariantCulture,
            $"| **total** | {manifest.Outputs.Count} | {manifest.Count(OutputFidelity.Exact)} " +
            $"| {manifest.Count(OutputFidelity.Canonical)} | {manifest.Count(OutputFidelity.Lossy)} " +
            $"| {manifest.Count(OutputFidelity.Generated)} " +
            $"| {manifest.Count(OutputFidelity.Unverified)} | {manifest.UnknownBytes} " +
            $"| {manifest.CodeBytes} | {manifest.UnexplainedBytes} |");

        text.AppendLine();
        text.AppendLine("## Editing");
        text.AppendLine();
        text.AppendLine("Every JSON file here is the editable source of truth for the bytes it came from.");
        text.AppendLine("Fields carry **domain** names; a field named `unknown_0xNN` is a byte whose meaning is");
        text.AppendLine("still open — it is carried as hex so the round trip closes, and it is counted.");
        text.AppendLine("A `.png` next to a `.json` is a generated view: edit the JSON, not the image.");
        text.AppendLine();
        text.AppendLine("To turn your edits back into files the 1991 binary loads:");
        text.AppendLine();
        text.AppendLine("```");
        text.AppendLine("cyac-transform --inverse <this directory> <output directory>");
        text.AppendLine("```");
        text.AppendLine();
        text.AppendLine("It rebuilds each `.lib` and `yeager.cfg` from this tree — the same code path");
        text.AppendLine("`--verify` proves, so an unedited tree rebuilds the originals byte for byte.");
        text.AppendLine("`yeager.exe` is not rebuilt: the transform unpacks it and does not re-pack it.");
        text.AppendLine();
        text.AppendLine("## Re-verifying");
        text.AppendLine();
        text.AppendLine("```");
        text.AppendLine("cyac-transform --verify <this directory>");
        text.AppendLine("```");
        text.AppendLine();
        text.AppendLine("re-encodes everything and diffs it against the originals recorded in `manifest.json`.");
        text.AppendLine("An unedited tree must verify clean; after an edit, a mismatch is expected exactly where");
        text.AppendLine("you edited and nowhere else.");

        return Encoding.UTF8.GetBytes(text.ToString());
    }
}
